const data = {
  products: [
    {
      name: "Jacket1",
      slug: "J1",
      category: "Jacket",
      image: "/images/p1.jpg",
      price: 120,
      countinStock: 10,
      brand: "Our",
      rating: 4.5,
      numReviews: 10,
      description: "High quality",
    },
    {
      name: "Jacket1",
      slug: "J2",
      category: "Jacket",
      image: "/images/p2.jpg",
      price: 120,
      countinStock: 10,
      brand: "Our",
      rating: 4.5,
      numReviews: 10,
      description: "High quality",
    },
    {
      name: "Jacket1",
      slug: "J3",
      category: "Jacket",
      image: "/images/p3.jpg",
      price: 120,
      countinStock: 10,
      brand: "Our",
      rating: 4.5,
      numReviews: 10,
      description: "High quality",
    },
    {
      name: "Jacket1",
      slug: "J4",
      category: "Jacket",
      image: "/images/p4.jpg",
      price: 120,
      countinStock: 10,
      brand: "Our",
      rating: 4.5,
      numReviews: 10,
      description: "High quality",
    },
  ],
};
export default data;
